'use client'

import { createContext, useCallback, useContext, useEffect, useMemo, useState, type ReactNode } from 'react'

export type AppLanguage = 'tr' | 'en'
export const english: Record<string, string> = {
  "Bir hafta biz": "One week of us",
  "7 gün: iyi ki mesaj atmışız.": "7 days: glad we sent that message.",
  "Aylık abonelik: biz": "Monthly plan: us",
  "30 gün birlikte. İptal tuşu nerede?": "30 days together. Where is the cancel button?",
  "Yüz kere iyi ki": "A hundred happy days",
  "100 gün, aynı favori insan.": "100 days, still your favorite person.",
  "Bir tur güneş": "One trip around the sun",
  "Bir yılı birlikte tamamladınız.": "One whole year together.",
  "İkinci sezon onaylandı": "Renewed for season two",
  "İki yıl oldu, hikâye hâlâ güzel.": "Two years, and the story is still good.",
  "Bin günlük takım": "The thousand-day team",
  "1000 gün aynı taraftasınız.": "1000 days on the same side.",
  "Beş yıllık klasik": "A five-year classic",
  "Birlikte yaklaşık beş yıl. Artık klasiksiniz.": "About five years together. A true classic.",
  "On yıllık efsane": "A ten-year legend",
  "Yaklaşık on yıl, hâlâ yan yana.": "About ten years, still side by side.",
  "İkinci oyuncu bağlandı": "Player two connected",
  "İlk oyunu birlikte tamamladınız.": "Your first game completed together.",
  "Rövanş lütfen": "Rematch, please",
  "3 oyun bitti. Skor kimde?": "3 games finished. Who is keeping score?",
  "Aynı takımdayız": "Same team",
  "5 oyunluk ortak macera.": "5 shared gaming adventures.",
  "Oyun gecesi müdavimleri": "Game night regulars",
  "10 oyun tamamlandı; kumandalar sıcak.": "10 games finished; controllers are warm.",
  "Yenilsek de beraber": "Together, even in defeat",
  "20 oyun, bol kahkaha.": "20 games and plenty of laughs.",
  "Kumanda paylaşımı uzmanı": "Controller-sharing experts",
  "35 oyunu birlikte bitirdiniz.": "35 games completed together.",
  "Elli oyunun hatırı": "Fifty games of memories",
  "50 ortak oyun. Mola versek mi?": "50 shared games. Time for a break?",
  "100 oyunluk güçlü bir takım.": "A strong team with 100 games.",
  "İlk durak": "First stop",
  "İlk yeni yerinizi birlikte keşfettiniz.": "Your first new place together.",
  "Evden çıkış başarılı": "Successfully left the house",
  "3 farklı yerde ortak anı.": "Shared memories in 3 places.",
  "Rota bizden sorulur": "We know the route",
  "5 yeni yer keşfedildi.": "5 new places discovered.",
  "Gezgin ikili": "Traveling duo",
  "10 durak, aynı yol arkadaşı.": "10 stops, the same travel partner.",
  "Haritada izimiz var": "Our mark on the map",
  "20 farklı yerde birlikteydiniz.": "Together in 20 different places.",
  "Bir sonraki durak neresi?": "Where to next?",
  "35 yeni yer. Rota uzuyor.": "35 new places. The route keeps growing.",
  "Elli duraklık hikâye": "A fifty-stop story",
  "50 ortak keşif tamamlandı.": "50 shared discoveries completed.",
  "Dünya küçük, biz büyük": "Small world, big adventures",
  "100 yerlik ortak bir yolculuk.": "A shared journey through 100 places.",
  "Bir bölüm daha ekibi": "The one-more-episode team",
  "İlk dizinizi birlikte bitirdiniz.": "Your first series finished together.",
  "Koltuk rezerve": "Couch reserved",
  "3 dizi tamamlandı, yerimiz belli.": "3 series finished; our seats are reserved.",
  "Spoiler yasak": "No spoilers allowed",
  "5 dizinin sonunu birlikte gördünüz.": "You reached 5 series finales together.",
  "10 dizi bitti. Uykuya da vakit var mı?": "10 series finished. Any time for sleep?",
  "20 ortak dizi macerası.": "20 shared series adventures.",
  "Bir sezon daha": "One more season",
  "35 dizi tamamlandı.": "35 series completed.",
  "Koltuk eleştirmenleri": "Couch critics",
  "50 dizilik ortak arşiv.": "A shared collection of 50 series.",
  "Dizi efsaneleri": "Series legends",
  "100 dizi! Kumanda artık sizi tanıyor.": "100 series! The remote knows you by now.",
  "İlk film bitti. Patlamış mısır kaldı mı?": "First movie finished. Any popcorn left?",
  "Film seçebildik": "We picked a movie",
  "3 film izlendi; seçim süresi sayılmaz.": "3 movies watched; choosing time does not count.",
  "Koltuk sineması": "Couch cinema",
  "5 ortak film gecesi.": "5 shared movie nights.",
  "Jeneriğe kadar beraber": "Together until the credits",
  "10 filmi birlikte tamamladınız.": "10 movies completed together.",
  "20 film, bolca konuşacak sahne.": "20 movies and plenty of scenes to discuss.",
  "Fragmana kanmadık": "Not fooled by the trailer",
  "35 film izlendi; favoriler belli oldu.": "35 movies watched; favorites are clear.",
  "Elli film biriktirdik": "Fifty movies collected",
  "50 film gecesinin hatırası.": "Memories of 50 movie nights.",
  "100 film! Ödül: bir film daha.": "100 movies! Your prize: another movie.",
  "İlk lokma ortak": "First shared bite",
  "İlk yeni lezzeti birlikte denediniz.": "Your first new food tried together.",
  "Bir çatal da senden": "A bite of yours too",
  "3 yeni tat keşfedildi.": "3 new tastes discovered.",
  "Menüye cesur bakış": "A brave look at the menu",
  "5 farklı lezzeti denediniz.": "5 different foods tried.",
  "10 yeni tat, ortak favoriler.": "10 new tastes and shared favorites.",
  "Her zamankinden farklı": "Something different",
  "20 lezzet keşfi tamamlandı.": "20 food discoveries completed.",
  "Tadım ekibi": "The tasting team",
  "35 yeni lezzet. Biraz da bana bırak.": "35 new foods. Save a little for me.",
  "50 ortak lezzet anısı.": "50 shared food memories.",
  "Sofranın efsaneleri": "Table legends",
  "100 yeni tat! Tatlıya yer kaldı mı?": "100 new tastes! Any room for dessert?",
  "Tamamlanan": "Completed",
  "Yapılan": "Done",
  "Yapıldı": "Done",
  "Gezilecek yer": "Place to visit",
  "Yaklaşan özel gün yok.": "No upcoming occasions.",
  "İlişki yolculuğunuzun dönüm noktaları": "Milestones in your relationship journey",
  "Kahveler hazır, heyecan yüksek.": "Coffee is ready, nerves are high.",
  "Bir söz, iki kocaman gülümseme.": "One promise, two big smiles.",
  "Yüzükler tamam, geri sayım başladı.": "Rings ready, countdown started.",
  "Biraz duygu, bolca dans.": "A little emotion, plenty of dancing.",
  "Aynı takım, artık aynı ev.": "Same team, now the same home.",
  "Tamam": "Done",
  "Sıradaki": "Up next",
  "Takvimle bağlantılı": "Linked to calendar",
  "Bu maddeyi kaldırırsan takvimdeki tarih korunur.": "Removing this item keeps its calendar date.",
  "1 istek": "1 wish",
  "Yükleniyor": "Loading",
  "Açılıyor": "Opening",
  "Hoş geldin": "Welcome",
  "Bir saniye...": "Just a moment...",
  "PIN’i ilk kez girdikten sonra Face ID açılacak.": "Face ID will be set up after your first PIN entry.",
  "Dört haneli PIN kodunu gir.": "Enter your four-digit PIN.",
  "Doğrulanıyor…": "Verifying…",
  "Face ID ile aç": "Unlock with Face ID",
  "Dört haneli PIN kodu": "Four-digit PIN",
  "PIN hatalı. Tekrar dene.": "Incorrect PIN. Try again.",
  "Face ID kurulamadı. PIN kodunu girerek devam et.": "Face ID setup failed. Enter your PIN to continue.",
  "Face ID iki kez doğrulanamadı. PIN kodunu gir.": "Face ID failed twice. Enter your PIN.",
  "Yüz tanınmadı. Bir kez daha dene.": "Face not recognized. Try once more.",
  "Ana Sayfa": "Home",
  "Yapılacaklar": "To-do",
  "İstekler": "Wishlist",
  "Başarımlar": "Achievements",
  "Takvim": "Calendar",
  "Ana menü": "Main menu",
  "Ayarlar": "Settings",
  "Ayarları aç": "Open settings",
  "Geri": "Back",
  "Görünüm": "Appearance",
  "Tema": "Theme",
  "Açık": "On",
  "Koyu": "Dark",
  "Dil": "Language",
  "Biz": "Us",
  "Birlikte başlangıç tarihi": "Together since",
  "İlk isim": "First name",
  "İkinci isim": "Second name",
  "Kilit ekranı": "Lock screen",
  "PIN kodu": "PIN code",
  "Değiştir": "Change",
  "Oluştur": "Create",
  "Kaldır": "Remove",
  "Kapalı": "Off",
  "açık": "on",
  "kapalı": "off",
  "Bildirimler": "Notifications",
  "Şifre dört rakam olmalı.": "The PIN must contain four digits.",
  "Etkin giriş şifresi doğru değil.": "The current PIN is incorrect.",
  "Şifreyi değiştir": "Change PIN",
  "Şifre oluştur": "Create PIN",
  "Uygulama girişinde kullanılacak dört haneli şifreyi gir.": "Enter a four-digit PIN to unlock the app.",
  "Yeni şifre": "New PIN",
  "İptal": "Cancel",
  "Kaydet": "Save",
  "Face ID kaldırılsın mı?": "Remove Face ID?",
  "Şifre kaldırılsın mı?": "Remove PIN?",
  "Devam etmek için etkin giriş şifreni gir.": "Enter your current PIN to continue.",
  "Etkin giriş şifresi": "Current PIN",
  "Vazgeç": "Cancel",
  "Uygulama sürümü {version}": "App version {version}",
  "{version} sürümünün bilgilerini aç": "Open release details for {version}",
  "Sürüm bilgileri": "Release details",
  "Kapat": "Close",
  "Bu sürümdeki yenilikler ve yayın bilgileri.": "What's new in this release and publication details.",
  "Sürüm": "Version",
  "Yayın tarihi": "Published on",
  "Yayın tarihi belirtilmedi.": "Publication date is unavailable.",
  "Neler değişti?": "What's changed?",
  "Takvim işlem butonları beyaz ikonlarla sadeleştirildi.": "Calendar action buttons were simplified with white icons.",
  "Yapılacaklar düzenleme modundaki açıklamalar kaldırıldı.": "The helper text in to-do editing mode has been removed.",
  "Takvime bağlı yerler silinince iki listeden, tamamlanınca takvimden kaldırılır.": "Linked places are removed from both lists when deleted, and from the calendar when completed.",
  "Takvimde tarih ve işlem butonlarından mercek kaldırıldı; Ekle ve Yönet ayrıldı.": "The calendar date and action lenses were removed; Add and Manage are now separate buttons.",
  "İstek ekleme butonu yuvarlak ve çerçeveli hale getirildi.": "The add-wish button is now round with a thin border.",
  "İki parmakla büyütme ve küçültme kapatıldı.": "Two-finger pinch zoom has been disabled.",
  "Yapılacaklar düzenleme modunda yalnızca silme için seçim yapılabilir.": "In to-do editing mode, items can only be selected for deletion.",
  "Sürüm bilgileri penceresi sadeleştirildi.": "The release details window has been simplified.",
  "Sürüm ve yayın tarihi aynı yazı stiliyle yan yana gösterilir.": "The version and publication date appear side by side with matching typography.",
  "Ayarlar’daki bilgi simgesine dokunarak sürüm ayrıntıları açılabilir.": "Tap the information icon in Settings to open release details.",
  "Sürümün yayın tarihi ve yapılan değişiklikler görüntülenebilir.": "The publication date and changes for the release are now displayed.",
  "Birlikte geçirdiğimiz": "Our time together",
  "gün": "days",
  "saat": "hours",
  "dakika": "minutes",
  "saniye": "seconds",
  "dk": "min",
  "sn": "sec",
  "Bir dahaki buluşma": "Our next meetup",
  "Bir dahaki buluşmaya kalan süre": "Time until our next meetup",
  "Kalan süre": "Time left",
  "Tarih": "Date",
  "Saat": "Time",
  "Buluşma tarihi": "Meetup date",
  "Buluşma saati": "Meetup time",
  "İstek ekle...": "Add a wish...",
  "İstek ekle": "Add wish",
  "Geri al": "Undo",
  "İstek silindi.": "Wish deleted.",
  "{count} istek silindi.": "{count} wishes deleted.",
  "{text} isteğini geri getir": "Restore wish: {text}",
  "Silinen istekler Geri al ile geri getirilebilir.": "Deleted wishes can be restored with Undo.",
  "İstekler ekranında isimler yukarı taşındı, metinler ortalandı ve buton çerçeveleri eşitlendi.": "Wishlist names have moved up, texts are centered, and button borders are consistent.",
  "{text} isteğini öncelikli yap": "Prioritize wish: {text}",
  "{text} isteğinin önceliğini kaldır": "Remove priority from wish: {text}",
  "İsteklere öncelik yıldızı eklendi.": "Priority stars have been added to wishes.",
  "Yıldızlı istekler üstte, tamamlanan istekler en altta gösterilir.": "Starred wishes appear first, while completed wishes remain at the bottom.",
  "Henüz istek yok.": "No wishes yet.",
  "İlk kişi": "First person",
  "İkinci kişi": "Second person",
  "{count} istek": "{count} wishes",
  "{name} için istek": "Wish for {name}",
  "{text} isteğini sil": "Delete wish: {text}",
  "{text} isteğini tamamla": "Complete wish: {text}",
  "{text} isteğini geri al": "Mark wish incomplete: {text}",
  "Yerler": "Places",
  "Oyunlar": "Games",
  "Diziler": "Series",
  "Filmler": "Movies",
  "Lezzetler": "Food",
  "Gezilecek Yerler": "Places to Visit",
  "Oynanacak Oyunlar": "Games to Play",
  "İzlenecek Diziler": "Series to Watch",
  "İzlenecek Filmler": "Movies to Watch",
  "Denenecek Lezzetler": "Food to Try",
  "Genel ilerleme": "Overall progress",
  "Tamamlanma oranı": "Completion rate",
  "Tümü": "All",
  "Ekle": "Add",
  "Silinecek maddeleri seç...": "Select items to delete...",
  "{category} ekle...": "Add {category}...",
  "{category} listesine ekle": "Add to {category}",
  "{text} maddesini silmek için seç": "Select {text} for deletion",
  "Seçilen {count} maddeyi sil": "Delete {count} selected items",
  "Maddeleri düzenle": "Edit items",
  "Düzenlemeyi bitir": "Finish editing",
  "Silmek istediklerini işaretle, sonra çöp kutusuna dokun.": "Select the items to delete, then tap the trash icon.",
  "Özel gün": "Special day",
  "Doğum günü": "Birthday",
  "Yıl dönümü": "Anniversary",
  "Birlikte plan": "Shared plan",
  "Kutlama": "Celebration",
  "İlk yıl dönümünüz": "Your first anniversary",
  "{count}. yıl dönümünüz": "Your anniversary: {count} years",
  "{name} {age} yaşına giriyor": "{name} turns {age}",
  "Bugün {date}": "Today is {date}",
  "İlişki takvimi": "Relationship calendar",
  "Önceki ay": "Previous month",
  "Sonraki ay": "Next month",
  "Takvim yükleniyor": "Loading calendar",
  "Özel gününüz": "Your special day",
  "Bugün": "Today",
  "Yönet": "Manage",
  "Bugün için takvimde özel bir tarih yok.": "No special occasions on this date.",
  "Özel günleri yönet": "Manage special days",
  "Eklediğin günleri düzenleyebilir veya kaldırabilirsin.": "Edit or remove the days you added.",
  "Yaklaşan özel günler": "Upcoming occasions",
  "Yaklaşan tarihler yükleniyor.": "Loading upcoming dates.",
  "Özel günü kaldır": "Remove special day",
  "“{title}” takvimden kaldırılsın mı?": "Remove “{title}” from the calendar?",
  "Her yıl tekrarlanan günleri de kaldırılır.": "Its yearly repeats will also be removed.",
  "Pencereyi kapat": "Close dialog",
  "Özel günü düzenle": "Edit special day",
  "Takvime özel gün ekle": "Add a special day",
  "Özel gün ekle": "Add a special day",
  "Birlikte hatırlayacağınız günü kaydet.": "Save a day to remember together.",
  "Günün adı": "Event name",
  "Günün adı...": "Event name...",
  "Örn. Orhan'ın doğum günü": "e.g. Orhan's birthday",
  "Tür": "Type",
  "Not": "Note",
  "(isteğe bağlı)": "(optional)",
  "Bir plan, hediye fikri veya hatırlamak istediğin detay…": "A plan, gift idea or a detail to remember…",
  "Her yıl tekrarla": "Repeat every year",
  "Değişiklikleri kaydet": "Save changes",
  "Takvime ekle": "Add to calendar",
  "Tarih belirtilmemiş": "No date specified",
  "Her yıl": "Yearly",
  "Düzenle": "Edit",
  "Günün adını ve geçerli bir tarih gir.": "Enter an event name and a valid date.",
  "Bu özel gün başka bir cihazda kaldırılmış. Pencereyi kapatıp yeni bir gün ekleyebilirsin.": "This occasion was removed on another device. Close this dialog and add a new day.",
  "{title} özel gününü düzenle": "Edit occasion: {title}",
  "{title} özel gününü kaldır": "Remove occasion: {title}",
  "İlişki": "Relationship",
  "Başarım ilerlemesi": "Achievement progress",
  "Kazanılan": "Unlocked",
  "Kazanılan başarım oranı": "Unlocked achievement rate",
  "Başarım ayrıntıları": "Achievement details",
  "Başarım kategorileri": "Achievement categories",
  "Tamamlanan yapılacaklar": "Completed to-dos",
  "Yapılacaklardan": "From your to-dos",
  "kazanıldı": "unlocked",
  "kilitli": "locked",
  "Kazanıldı": "Unlocked",
  "{count}% tamamlandı": "{count}% complete",
  "İlişki yolculuğunuz": "Your relationship journey",
  "Dönüm noktaları": "Milestones",
  "İsteme": "Proposal",
  "Söz": "Promise ceremony",
  "Nişan": "Engagement",
  "Kına": "Henna night",
  "Evlilik": "Marriage",
  "önceki adım tamamlanmalı": "complete the previous step first",
  "Çocuk": "Child",
  "Sonsuza kadar kilitli": "Forever locked",
  "Çocuk, sonsuza kadar kilitli": "Child, forever locked",
  "yer": "places",
  "oyun": "games",
  "dizi": "series",
  "film": "movies",
  "lezzet": "foods",
  "Buluşma bildirimleri": "Meetup notifications",
  "Buluşma gününe kalan süreyi seçtiğin saatte bildirir.": "Notifies you at your chosen time with the days until your meetup.",
  "Takvim hatırlatmaları": "Calendar reminders",
  "Takvimdeki günler için 14, 7 ve 1 gün kala bildirir.": "Notifies you 14, 7 and 1 day before calendar occasions.",
  "Takvim hatırlatmaları açık.": "Calendar reminders are on.",
  "Takvim hatırlatmaları kapalı.": "Calendar reminders are off.",
  "Bildirimler bu cihazda henüz kullanılamıyor.": "Notifications are not available on this device yet.",
  "Bildirim izni verilmedi.": "Notification permission was not granted.",
  "Geçersiz bildirim aboneliği": "Invalid notification subscription",
  "Buluşma bildirimleri açık.": "Meetup notifications are on.",
  "Bildirimler açılamadı. Lütfen yeniden dene.": "Could not enable notifications. Please try again.",
  "Buluşma bildirimleri kapalı.": "Meetup notifications are off.",
  "Bildirimler kapatılamadı. Lütfen yeniden dene.": "Could not disable notifications. Please try again.",
  "Bildirim ayarı değiştirilemedi. Lütfen yeniden dene.": "Could not change the notification setting. Please try again.",
  "Eşitleme hazırlanıyor…": "Preparing sync…",
  "Eşitleme bekliyor:": "Sync pending:",
  "Eşitleme sırasında başka bir cihazdan gelen değişiklikler çakıştı. Yeniden deneyin.": "Changes conflicted with another device during sync. Please try again.",
  "Değişiklik eşitlenemedi.": "Could not sync the change.",
  "Uzak kayıt yenilenemedi.": "Could not refresh shared data.",
  "Canlı eşitleme bağlantısı kurulamadı.": "Could not connect to live sync.",
  "Eşitleme bağlantısı kurulamadı.": "Could not connect to sync.",
  "İlk 100 gün": "First 100 days",
  "Birlikte nice güzel günlere": "To many happy days together",
  "İlk yılınız": "Your first year",
  "Bir yıl, binlerce güzel an": "One year, thousands of lovely moments",
  "500 gün": "500 days",
  "Her gün biraz daha yakın": "Closer every day",
  "İki yıl": "Two years",
  "Hikâyeniz büyümeye devam ediyor": "Your story keeps growing",
  "1000 gün": "1000 days",
  "Bin gün, tek güzel hikâye": "A thousand days, one lovely story",
  "1500 gün": "1500 days",
  "Birlikte nice mevsimler geride kaldı": "So many seasons together",
  "İki bin gün": "Two thousand days",
  "Her gün seçilen aynı güzel hikâye": "Choosing the same lovely story every day",
  "3000 gün": "3000 days",
  "Bir ömre sığacak kadar çok anı": "A lifetime of memories",
  "İlk oyun": "First game",
  "İlk ortak oyun macerası": "Your first gaming adventure",
  "Beş oyun": "Five games",
  "Rövanşlar sırada": "Time for a rematch",
  "İlk 10 oyun": "First 10 games",
  "Tatlı bir rekabet başladı": "A friendly rivalry begins",
  "Oyun arkadaşı": "Gaming partners",
  "25 oyunda aynı takım": "On the same team for 25 games",
  "Oyun gecesi ustaları": "Game night masters",
  "Birlikte 50 oyun tamamlandı": "50 games completed together",
  "Rövanş bitmez": "Endless rematches",
  "Yetmiş beş oyunda aynı takım": "Same team for 75 games",
  "Yüzüncü zafer": "Hundredth victory",
  "Yüz oyuna ulaşmak sabır ister": "100 games takes dedication",
  "Efsane ikili": "Legendary duo",
  "Yüz elli ortak oyun tamamlandı": "150 games completed together",
  "İlk keşif": "First discovery",
  "İlk yeni yerinizi birlikte gördünüz": "Your first new place together",
  "İlk keşifler": "Early discoveries",
  "Birlikte 5 yeni yer": "5 new places together",
  "Gezgin çift": "Traveling couple",
  "10 yerde ortak bir anı": "Shared memories in 10 places",
  "20 yer, tek hikâye": "20 places, one story",
  "Birlikte nice yollar keşfettiniz": "So many paths explored together",
  "50 yer": "50 places",
  "Birlikte keşfedilecek daha çok yer var": "So much more to explore together",
  "Yolların ustası": "Masters of the road",
  "Yetmiş beş farklı yerde anı biriktirin": "Make memories in 75 places",
  "Yüz durak": "A hundred stops",
  "Yüz ayrı keşif, tek ortak hikâye": "100 discoveries, one shared story",
  "Dünya sizin": "The world is yours",
  "Yüz elli yeni yer keşfedildi": "150 new places discovered",
  "İlk bölüm": "First episode",
  "İlk dizinize birlikte başladınız": "Your first series together",
  "Üç bölüm daha": "Three more episodes",
  "Bölüm sonu sürprizlerine hazır olun": "Ready for cliffhangers",
  "Dizi keyfi": "Series time",
  "Birlikte beş dizi tamamlandı": "5 series finished together",
  "Dizi maratonu": "Series marathon",
  "On dizi, bolca güzel akşam": "10 series, many lovely evenings",
  "Jenerik ezberi": "Know the credits",
  "Birlikte yirmi dizi macerası": "20 series adventures together",
  "Bir bölüm daha": "One more episode",
  "Otuz dizi birlikte tamamlandı": "30 series finished together",
  "Dizi arşivi": "Series collection",
  "Elli ortak dizi macerası": "50 shared series adventures",
  "Jenerik uzmanları": "Credits experts",
  "Yetmiş beş dizinin sonuna birlikte": "75 series endings together",
  "İlk film gecesi": "First movie night",
  "Atıştırmalıklar hazır": "Snacks are ready",
  "Beş film": "Five movies",
  "Koltukta en güzel eşlik": "The best company on the couch",
  "Film seçme ustaları": "Movie picking masters",
  "On ortak film gecesi": "10 shared movie nights",
  "Jenerik bitene kadar": "Until the credits end",
  "Yirmi beş film birlikte izlendi": "25 movies watched together",
  "Sinema kulübü": "Movie club",
  "Ellinci filminiz kutlu olsun": "Happy 50th movie",
  "Yetmiş beş film": "Seventy-five movies",
  "Her film yeni bir ortak anı": "Every movie, a new shared memory",
  "Yüzüncü film": "Hundredth movie",
  "Yüz film gecesini birlikte tamamlayın": "Complete 100 movie nights together",
  "Beyaz perde efsaneleri": "Screen legends",
  "Yüz elli film, sayısız güzel sahne": "150 movies, countless lovely scenes",
  "İlk yeni lezzet": "First new taste",
  "İlk ortak tat keşfi": "Your first taste discovery",
  "Beş yeni tat": "Five new tastes",
  "Damak tadınız birlikte gelişiyor": "Your tastes grow together",
  "Lezzet avcıları": "Taste hunters",
  "On farklı tat birlikte denendi": "10 tastes tried together",
  "Menüde ne varsa": "Everything on the menu",
  "Yirmi yeni lezzet keşfedildi": "20 new foods discovered",
  "Gurme çift": "Gourmet couple",
  "Birlikte elli lezzet anısı": "50 tasty memories together",
  "Lezzet kâşifleri": "Flavor explorers",
  "Yetmiş beş yeni tat keşfedildi": "75 new tastes discovered",
  "Yüzüncü tat": "Hundredth taste",
  "Yüz ayrı lezzeti birlikte deneyin": "Try 100 different foods together",
  "Gurme efsaneleri": "Gourmet legends",
  "Yüz elli lezzet, ortak sofrada": "150 foods at your shared table"
}
export function translate(language: AppLanguage, text: string, values: Record<string, string | number> = {}) {
  const template = language === 'en' ? english[text] ?? text : text
  return template.replace(/\{(\w+)\}/g, (match, key: string) => String(values[key] ?? match))
}
type LanguageContextValue = {
  language: AppLanguage
  locale: string
  setLanguage: (language: AppLanguage) => void
  t: (text: string, values?: Record<string, string | number>) => string
}
const LanguageContext = createContext<LanguageContextValue | null>(null)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, updateLanguage] = useState<AppLanguage>('tr')
  useEffect(() => {
    try { updateLanguage(localStorage.getItem('soapp-language') === 'en' ? 'en' : 'tr') } catch {}
  }, [])
  const setLanguage = useCallback((next: AppLanguage) => {
    try { localStorage.setItem('soapp-language', next) } catch {}
    updateLanguage(next)
  }, [])
  useEffect(() => { document.documentElement.lang = language }, [language])
  const t = useCallback((text: string, values?: Record<string, string | number>) => translate(language, text, values), [language])
  const value = useMemo(() => ({ language, locale: language === 'tr' ? 'tr-TR' : 'en-GB', setLanguage, t }), [language, setLanguage, t])
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) throw new Error('useLanguage must be used within LanguageProvider')
  return context
}
